#version: '3.8'
services:
  # Dashboard
  grafana_ee4216:
    image: grafana/grafana
    container_name: grafana_ee4216
    restart: always
    entrypoint: >
      /bin/sh -c "
      cd /var/lib/grafana &&
      mkdir -p dashboards &&
      /run.sh"
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_ee4216/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - TZ=UTC-8
    networks:
      - iot_net

  # Mock Insertion
  mock_insertion:
    build:
      context: ./mock_insertion
    container_name: mock_insertion
    restart: always
    volumes:
      - ./prometheus_data:/prometheus_data
    environment:
      - TZ=UTC-8
    networks:
      - iot_net

  # Prometheus/Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    ports:
      - '9090:9090'
    networks:
      - iot_net 

  # Prometheus/Prometheus-Exporter
  prometheus-exporter:
    build:
      context: ./prometheus/prometheus-exporter
    container_name: prometheus-exporter
    restart: always
    volumes:
      - ./prometheus_data:/prometheus_data
    ports:
      - '9092:9092'
    environment:
      - TZ=UTC-8
    networks:
      - iot_net

  # Prometheus-Gateway/Mosquitto
  mosquitto:
    build:
      context: ./prometheus-gateway/mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ./prometheus-gateway/mosquitto/config:/mosquitto/config
      - ./prometheus-gateway/mosquitto/log:/mosquitto/log
      - ./prometheus_data:/prometheus_data
    ports:
      - '1883:1883'
    environment:
      - TZ=UTC-8
    networks:
      - iot_net

  # Prometheus-Gateway/HTTP
  http-post:
    build:
      context: ./prometheus-gateway/http
    container_name: http-post
    restart: always
    volumes:
      - ./prometheus_data:/prometheus_data
      - ./grafana_ee4216/provisioning/datasources/images:/images
    ports:
      - '1884:1884'
    environment:
      - TZ=UTC-8
    networks:
      - iot_net

volumes:
  grafana-storage: {}
  prometheus: {}

networks:
  iot_net:
    driver: bridge
