#version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana_ee4216
    restart: always
    entrypoint: >
      /bin/sh -c "
      cd /var/lib/grafana &&
      mkdir -p dashboards &&
      /run.sh"
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_ee4216/provisioning/:/etc/grafana/provisioning/
    networks:
      - iot_net

volumes:
  grafana-storage: {}

networks:
  iot_net:
